{
    "user": {
        "nombres": "Diego Agustín",
        "apellidos": "Zabala",
        "telefono": "2615553947",
        "email": "diego@test.com",
        "password": "123456",
        "address": {
            "calle": "Salta",
            "numero": 456,
            "localidad": "Godoy Cruz",
            "geolocalizacion": "65465 46546",
            "activo": 1
        },
        "activo": 1,
        "fecha_modificacion": "19/08/2020 10:59:32",
        "fk_id_rol_usuario": 1
    }
}